### ISSUE TITLE
aladhan.com blocked from my country (AU)

### ISSUE THREAD

**Issue by talondnb** [islamic-network/aladhan.com#22]
Assallam,

It seems a few people have this issue, I figured I would report here too. I cannot access aladhan.com from multiple AU IP's but I can access it from a Ukraine IP range fine. Is there some sort of geo blocking occurring now?

This has also affected a few Home Assistant users for the Islamic Prayer times integration which uses the aladhan.com API.

**Comment by meezaan** [comment]
Alaykum Salaam @talondnb. We changed DNS after a surge because Cloudlfare started to have some problems. It has not yet propagated https://www.digwebinterface.com/?hostnames=aladhan.com&type=NS&useresolver=8.8.4.4&ns=all&nameservers=.

Once DNS propagates, everything should be back up. This is not an option for everyone, but if you set the public DNS server to one of those that are propagated, you should be able to access instantly.
