### ISSUE TITLE
Unable to retrive Api response, 302 Error

### ISSUE THREAD

**Issue by MuzammilPatel** [islamic-network/aladhan.com#45]
Asalamu Alaikum, 

Background: I am trying to use the below API to get prayer and Hijri date for Melbourne, Australia using an ESP32 Dev kit which is connected to my local Wifi. 

http://api.aladhan.com/v1/timingsByCity?city=Melbourne&country=Australia&method=4&timezonestring=Australia/Melbourne

When using the above API directly on Chrome, I can see that it gets a response and all the JSON information is posted, but using the same gives me a 302 error while running on the code. 

Function that I am using: 

```
void fetchData(){
  
  if (WiFi.status() == WL_CONNECTED) {
    HTTPClient http;
    Serial.print("[HTTP] begin...\n");
    http.begin("http://api.aladhan.com/v1/timingsByCity?city=Melbourne&country=Australia&method=4&timezonestring=Australia/Melbourne");
    int httpCode = http.GET();

    // HTTP header has been send and Server response header has been handled
    Serial.printf("[HTTP] GET... code: %d\n", httpCode);
    
    String payload = http.getString();        
    Serial.println("Response payload:");
    Serial.println(payload);
    http.end();
  }
}
```
Can you please guide where the issue is.

Jazak Allah

**Comment by meezaan** [comment]
3laykum salaam! Please see the API docs at https://aladhan.com/prayer-times-api#tag/Daily-Prayer-Times/paths/~1v1~1timingsByCity~1%7Bdate%7D/get.

You are using the old URLs which are redirected to the updated URLs (which are RESTful) in order to provide backward compatibility (this change was made over a year ago). So you can either switch to the new URLs where the date is required explicitly or tell the `HTTPClient` to follow redirects.

Even in Chrome, you will see that your URL changes before the response appears, because Chrome follows the HTTP 302 redirect.

**Comment by MuzammilPatel** [comment]
JazakAllah khairan. 

It's working now.
